extends Node
## Music and sound effects. Gameplay calls `AudioService.play(&"id")` at event points and
## directors pick the music; this service owns buses, voice pooling, spam throttling,
## crossfades and the volume settings. All audio is generated by tools/audio/build.py.

const MUSIC_DIR := "res://assets/audio/music/%s.wav"
const SFX_DIR := "res://assets/audio/sfx/%s.wav"
const MUSIC := [&"title", &"stage1", &"boss", &"stage2", &"stage3", &"stage_clear", &"mission_complete"]
const SFX := [
	&"shot_player", &"shot_enemy", &"shot_heavy", &"laser", &"explosion_small", &"explosion_large",
	&"explosion_huge", &"hit", &"armor_ping", &"player_hurt", &"player_death", &"jump", &"double_jump",
	&"dash", &"land", &"heavy_land", &"pickup", &"weapon_get", &"checkpoint", &"ui_move", &"ui_confirm",
	&"ui_back", &"warning", &"charge", &"beam", &"transform", &"boost", &"door",
]
## Minimum seconds between two plays of the same effect (rapid fire, many explosions).
const MIN_GAP := {
	&"shot_player": 0.07, &"laser": 0.06, &"shot_enemy": 0.05, &"hit": 0.045, &"armor_ping": 0.12,
	&"explosion_small": 0.06, &"explosion_large": 0.1, &"explosion_huge": 0.25, &"pickup": 0.05,
	&"ui_move": 0.03, &"land": 0.1, &"dash": 0.1,
}
## Per-effect trim so the mix sits right (dB).
const TRIM := {
	&"shot_player": -9.0, &"laser": -10.0, &"shot_enemy": -8.0, &"hit": -6.0, &"explosion_small": -4.0,
	&"ui_move": -8.0, &"pickup": -5.0, &"land": -4.0, &"armor_ping": -8.0,
}
const VOICES := 24
const MUSIC_BASE_DB := -7.0

var current_music: StringName = &""

var _music_streams: Dictionary = {}
var _sfx_streams: Dictionary = {}
var _voices: Array[AudioStreamPlayer] = []
var _next_voice: int = 0
var _last_played: Dictionary = {}
var _music_a: AudioStreamPlayer
var _music_b: AudioStreamPlayer
var _jingle: AudioStreamPlayer
var _music_tween: Tween
var _active_music: AudioStreamPlayer
var _clock: float = 0.0
## Headless runs (tests, CI, boot check) have no audio device: the dummy driver never retires
## playbacks, so voices are tracked but never started.
var _silent: bool = false


func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	_silent = DisplayServer.get_name() == "headless"
	for bus in [&"Music", &"SFX", &"UI"]:
		if AudioServer.get_bus_index(bus) == -1:
			AudioServer.add_bus()
			var i := AudioServer.bus_count - 1
			AudioServer.set_bus_name(i, bus)
			AudioServer.set_bus_send(i, &"Master")
	for id: StringName in MUSIC:
		_music_streams[id] = _load(MUSIC_DIR % id)
	for id: StringName in SFX:
		_sfx_streams[id] = _load(SFX_DIR % id)
	_music_a = _player(&"Music")
	_music_b = _player(&"Music")
	_jingle = _player(&"Music")
	for i in VOICES:
		_voices.append(_player(&"SFX"))
	Settings.changed.connect(_apply_volumes)
	_apply_volumes()


func _process(delta: float) -> void:
	_clock += delta


func _exit_tree() -> void:
	# Release every stream so nothing is reported as leaked at shutdown.
	if _music_tween:
		_music_tween.kill()
	for child in get_children():
		if child is AudioStreamPlayer:
			(child as AudioStreamPlayer).stop()
			(child as AudioStreamPlayer).stream = null
			child.free()
	_voices.clear()
	_music_streams.clear()
	_sfx_streams.clear()


## One-shot effect. `pitch_jitter` varies pitch slightly so repeats never sound identical.
func play(id: StringName, volume_db: float = 0.0, pitch_jitter: float = 0.05) -> void:
	var stream: AudioStream = _sfx_streams.get(id)
	if stream == null:
		push_error("AudioService: unknown sound '%s'." % id)
		return
	var gap: float = MIN_GAP.get(id, 0.03)
	if _clock - float(_last_played.get(id, -1.0)) < gap:
		return
	_last_played[id] = _clock
	var voice := _voices[_next_voice]
	_next_voice = (_next_voice + 1) % _voices.size()
	voice.bus = &"UI" if String(id).begins_with("ui_") else &"SFX"
	voice.stream = stream
	voice.volume_db = volume_db + float(TRIM.get(id, 0.0))
	voice.pitch_scale = 1.0 + randf_range(-pitch_jitter, pitch_jitter)
	if not _silent:
		voice.play()


## Explosion sound matched to an effect's visual size.
func play_explosion(size: float) -> void:
	if size < 1.3:
		play(&"explosion_small")
	elif size < 3.0:
		play(&"explosion_large")
	else:
		play(&"explosion_huge")


## Crossfades to a looping track; replaying the current track does nothing.
func play_music(id: StringName, fade: float = 1.2) -> void:
	if id == current_music:
		return
	var stream: AudioStream = _music_streams.get(id)
	if stream == null:
		push_error("AudioService: unknown music '%s'." % id)
		return
	current_music = id
	var incoming := _music_b if _active_music == _music_a else _music_a
	var outgoing := _active_music
	_active_music = incoming
	incoming.stream = stream
	incoming.volume_db = -60.0
	if not _silent:
		incoming.play()
	_fade(incoming, outgoing, fade)


func stop_music(fade: float = 1.0) -> void:
	current_music = &""
	_fade(null, _active_music, fade)
	_active_music = null


## Short fanfare over the music: the loop ducks and comes back afterwards.
func play_jingle(id: StringName) -> void:
	var stream: AudioStream = _music_streams.get(id)
	if stream == null:
		push_error("AudioService: unknown jingle '%s'." % id)
		return
	_jingle.stream = stream
	_jingle.volume_db = 0.0
	if not _silent:
		_jingle.play()
	var active := _active_music
	if active and active.playing:
		var duck := create_tween()
		duck.tween_property(active, "volume_db", -24.0, 0.25)
		duck.tween_interval(maxf(0.5, stream.get_length() - 1.5))
		duck.tween_property(active, "volume_db", 0.0, 1.0)


func _fade(incoming: AudioStreamPlayer, outgoing: AudioStreamPlayer, fade: float) -> void:
	if _music_tween:
		_music_tween.kill()
	var fade_out := outgoing != null and outgoing.playing
	if incoming == null and not fade_out:
		return
	_music_tween = create_tween().set_parallel()
	if incoming:
		_music_tween.tween_property(incoming, "volume_db", 0.0, fade)
	if fade_out:
		_music_tween.tween_property(outgoing, "volume_db", -60.0, fade)
		_music_tween.chain().tween_callback(outgoing.stop)


func _apply_volumes() -> void:
	_set_bus(&"Music", Settings.music_volume, MUSIC_BASE_DB)
	_set_bus(&"SFX", Settings.sfx_volume, 0.0)
	_set_bus(&"UI", Settings.sfx_volume, -2.0)


func _set_bus(bus: StringName, linear: float, base_db: float) -> void:
	var i := AudioServer.get_bus_index(bus)
	AudioServer.set_bus_mute(i, linear <= 0.001)
	AudioServer.set_bus_volume_db(i, base_db + linear_to_db(maxf(linear, 0.001)))


func _player(bus: StringName) -> AudioStreamPlayer:
	var p := AudioStreamPlayer.new()
	p.bus = bus
	add_child(p)
	return p


func _load(path: String) -> AudioStream:
	var stream := load(path) as AudioStream
	if stream == null:
		push_error("AudioService: missing audio file '%s' (run tools/audio/build.py)." % path)
	return stream
