class_name RetroArt
extends RefCounted
## Stage 4 pixel art (assets/retro, generated by tools/pixel/build.py) and the 8-bit screen size.

const SCREEN := Vector2(256, 224)
## Top HUD band height; the playfield is below it.
const HUD_H := 16.0
const DIR := "res://assets/retro/%s.png"
## Frame counts of each sprite sheet (frames laid out left to right).
const FRAMES := {
	&"player": 2, &"enemy_drone": 2, &"enemy_dart": 2, &"enemy_pod": 2, &"enemy_heavy": 2,
	&"enemy_turret": 2, &"explosion": 4, &"explosion_big": 4, &"capsule": 2, &"heart": 2,
	&"boss": 2, &"shot_enemy": 2, &"tiles": 6,
}

static var _cache: Dictionary = {}


static func texture(sheet: StringName) -> Texture2D:
	if not _cache.has(sheet):
		var tex := load(DIR % sheet) as Texture2D
		if tex == null:
			push_error("RetroArt: missing sprite sheet '%s'." % sheet)
		_cache[sheet] = tex
	return _cache[sheet]


static func sprite(sheet: StringName) -> Sprite2D:
	var s := Sprite2D.new()
	s.texture = texture(sheet)
	s.hframes = FRAMES.get(sheet, 1)
	return s
